spring:
  application:
    name: AdminService
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500    
      config:
        enabled: true
        prefix: configuration
        defaultContext: apps
        profileSeparator: '::'
      discovery:
        register: true
        healthCheckPath: ${management.contextPath}/system/health
        healthCheckInterval: 15s
